
version: 0.1
phases:
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install sbt
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt compile
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
