
version: 0.1
phases:
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install sbt
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt compile
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
      - export ARTIFACT=target/scala-2.12/HelloHandler-assembly-0.1.0-SNAPSHOT.jar
      - export ARTIFACT_HASH=$(md5sum $ARTIFACT | cut -f1 -d" ")
      - mkdir -p deploy/$ARTIFACT_HASH
      - cp $ARTIFACT deploy/$ARTIFACT_HASH
artifacts:
  files:
    - deploy/**/*
