
version: 0.1
phases:
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install sbt
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt compile
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p deploy/$(md5sum target/scala-2.12/HelloHandler-assembly-0.1.0-SNAPSHOT.jar | cut -f1 -d" ")
      - cp target/scala-2.12/HelloHandler-assembly-0.1.0-SNAPSHOT.jar deploy/$(md5sum target/scala-2.12/HelloHandler-assembly-0.1.0-SNAPSHOT.jar | cut -f1 -d" ")/HelloHandler.jar
artifacts:
  files:
    - deploy/**/*
