
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A hello world lambda
Resources:
  Hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: net.mcarolan.HelloLambda
      Runtime: java8
      CodeUri: deploy
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::149271426415:role/lambda-execute-role'
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
